# Generated by Django 2.1 on 2018-08-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0004_auto_20180804_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='posts.ReceivedLikes', to='users.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='receivedlikes',
            unique_together={('post', 'profile')},
        ),
    ]
