# Generated by Django 2.1 on 2018-08-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180806_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
